// https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html
// https://www.jetbrains.com/help/idea/http-response-handling-examples.html#checking-response-headers-body

### Suche mit vorhandener flotte-ID
GET {{baseUrl}}/rest/00000000-0000-0000-0000-000000000001
Accept: application/json

### Suche mit nicht-vorhandener flotte-ID: 404 (Not Found)
GET {{baseUrl}}/ffffffff-ffff-ffff-ffff-ffffffffffff
