// https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html
// https://www.jetbrains.com/help/idea/http-response-handling-examples.html#checking-response-headers-body

### Suche alle flotten (<Strg><Click> fuer Web Browser)
GET {{baseUrl}}/rest
Accept: application/json
